---
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    csvfile: "{{ lookup('file', 'example.csv') }}"

  tasks:
    - name: Parse CSV To YAML
      template:
        src: "./test.j2"
        dest: "./vars.yml"
      run_once: true
